//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Swsu.Lignis.RolePermissionsConfigurator.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PostgreSQLErrorCodes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PostgreSQLErrorCodes() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Swsu.Lignis.RolePermissionsConfigurator.Resources.PostgreSQLErrorCodes", typeof(PostgreSQLErrorCodes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка соединения (Код ошибки: 08000).
        /// </summary>
        internal static string Err08000 {
            get {
                return ResourceManager.GetString("Err08000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Соединение не существует (Код ошибки: 08003).
        /// </summary>
        internal static string Err08003 {
            get {
                return ResourceManager.GetString("Err08003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка соединения (Код ошибки: 08006).
        /// </summary>
        internal static string Err08006 {
            get {
                return ResourceManager.GetString("Err08006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка авторизации: неверные параметры подключения (Код ошибки: 28000).
        /// </summary>
        internal static string Err28000 {
            get {
                return ResourceManager.GetString("Err28000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка авторизации: указан неверный логин или пароль (Код ошибки: 28P01).
        /// </summary>
        internal static string Err28P01 {
            get {
                return ResourceManager.GetString("Err28P01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка обращения к БД: указано неверное имя базы данных (Код ошибки: 3D000).
        /// </summary>
        internal static string Err3D000 {
            get {
                return ResourceManager.GetString("Err3D000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка обращения к БД: указано неверное имя схемы (Код ошибки: 3F000).
        /// </summary>
        internal static string Err3F000 {
            get {
                return ResourceManager.GetString("Err3F000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка SQL-запроса: указан неверный синтаксис (Код ошибки: 42601).
        /// </summary>
        internal static string Err42601 {
            get {
                return ResourceManager.GetString("Err42601", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка соединения: в данный момент сервер БД недоступен (Код ошибки: 57P03).
        /// </summary>
        internal static string Err57P03 {
            get {
                return ResourceManager.GetString("Err57P03", resourceCulture);
            }
        }
    }
}
